### PR TITLE
fix(api-base): resolve resource promises in parallel

### LINKED ISSUE #2: `console.log` is a little verbose when using `deno`
Amazingly, the yowasp npm package works great with Deno; the [test module](https://github.com/YoWASP/yosys/blob/develop/npmjs/test/test_api.mjs) works out of the box with only a single line change to the import statement:

```javascript
import { runYosys } from 'npm:@yowasp/yosys';
```

Deno is very close to a typical browser environment by design, and most of the code is just pure javascript, so this is all pretty nice. However, it *does* cause a lot of `console.log` usage under the CLI:

```
austin@GANON:~/tmp/deno-yowasp$ deno run -A main.ts
[YoWASP runtime] Fetching resource bundle file:///home/austin/.cache/deno/npm/registry.npmjs.org/@yowasp/yosys/0.37.58-dev.635/gen/resources-yosys.js
[YoWASP runtime] Fetching resource bundle file:///home/austin/.cache/deno/npm/registry.npmjs.org/@yowasp/yosys/0.37.58-dev.635/gen/resources-yosys.js
[YoWASP runtime] Fetching resource file file:///home/austin/.cache/deno/npm/registry.npmjs.org/@yowasp/yosys/0.37.58-dev.635/gen/yosys.core.wasm
[YoWASP runtime] Fetching resource file file:///home/austin/.cache/deno/npm/registry.npmjs.org/@yowasp/yosys/0.37.58-dev.635/gen/yosys.core.wasm
[YoWASP runtime] Fetching resource file file:///home/austin/.cache/deno/npm/registry.npmjs.org/@yowasp/yosys/0.37.58-dev.635/gen/yosys.core2.wasm
[YoWASP runtime] Fetching resource file file:///home/austin/.cache/deno/npm/registry.npmjs.org/@yowasp/yosys/0.37.58-dev.635/gen/yosys.core2.wasm
[YoWASP runtime] Fetching resource file file:///home/austin/.cache/deno/npm/registry.npmjs.org/@yowasp/yosys/0.37.58-dev.635/gen/yosys.core3.wasm
[YoWASP runtime] Fetching resource file file:///home/austin/.cache/deno/npm/registry.npmjs.org/@yowasp/yosys/0.37.58-dev.635/gen/yosys.core3.wasm
[YoWASP runtime] Fetching resource file file:///home/austin/.cache/deno/npm/registry.npmjs.org/@yowasp/yosys/0.37.58-dev.635/gen/yosys.core4.wasm
[YoWASP runtime] Fetching resource file file:///home/austin/.cache/deno/npm/registry.npmjs.org/@yowasp/yosys/0.37.58-dev.635/gen/share/ice40/cells_sim.v
[YoWASP runtime] Fetching resource file file:///home/austin/.cache/deno/npm/registry.npmjs.org/@yowasp/yosys/0.37.58-dev.635/gen/yosys.core4.wasm
[YoWASP runtime] Fetching resource file file:///home/austin/.cache/deno/npm/registry.npmjs.org/@yowasp/yosys/0.37.58-dev.635/gen/share/ice40/cells_sim.v
[YoWASP runtime] Fetching resource file file:///home/austin/.cache/deno/npm/registry.npmjs.org/@yowasp/yosys/0.37.58-dev.635/gen/share/nexus/cells_xtra.v
[YoWASP runtime] Fetching resource file file:///home/austin/.cache/deno/npm/registry.npmjs.org/@yowasp/yosys/0.37.58-dev.635/gen/share/nexus/cells_xtra.v
[YoWASP runtime] Fetching resource file file:///home/austin/.cache/deno/npm/registry.npmjs.org/@yowasp/yosys/0.37.58-dev.635/gen/share/quicklogic/qlf_k6n10f/bram_types_sim.v
[YoWASP runtime] Fetching resource file file:///home/austin/.cache/deno/npm/registry.npmjs.org/@yowasp/yosys/0.37.58-dev.635/gen/share/quicklogic/qlf_k6n10f/bram_types_sim.v
[YoWASP runtime] Fetching resource file file:///home/austin/.cache/deno/npm/registry.npmjs.org/@yowasp/yosys/0.37.58-dev.635/gen/share/quicklogic/qlf_k6n10f/brams_sim.v
[YoWASP runtime] Fetching resource file file:///home/austin/.cache/deno/npm/registry.npmjs.org/@yowasp/yosys/0.37.58-dev.635/gen/share/quicklogic/qlf_k6n10f/brams_sim.v
[YoWASP runtime] Fetching resource file file:///home/austin/.cache/deno/npm/registry.npmjs.org/@yowasp/yosys/0.37.58-dev.635/gen/share/xilinx/cells_sim.v
[YoWASP runtime] Fetching resource file file:///home/austin/.cache/deno/npm/registry.npmjs.org/@yowasp/yosys/0.37.58-dev.635/gen/share/xilinx/cells_sim.v
[YoWASP runtime] Fetching resource file file:///home/austin/.cache/deno/npm/registry.npmjs.org/@yowasp/yosys/0.37.58-dev.635/gen/share/xilinx/cells_xtra.v
[YoWASP runtime] Fetching resource file file:///home/austin/.cache/deno/npm/registry.npmjs.org/@yowasp/yosys/0.37.58-dev.635/gen/share/xilinx/cells_xtra.v

 /----------------------------------------------------------------------------\
 |                                                                            |
 |  yosys -- Yosys Open SYnthesis Suite                                       |
 |                                                                            |
 |  Copyright (C) 2012 - 2020  Claire Xenia Wolf <claire@yosyshq.com>         |
 |                                                                            |
 |  Permission to use, copy, modify, and/or distribute this software for any  |
 |  purpose with or without fee is hereby granted, provided that the above    |
 |  copyright notice and this permission notice appear in all copies.         |
 |                                                                            |
 |  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES  |
 |  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF          |
 |  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR   |
 |  ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES    |
 |  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN     |
 |  ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF   |
 |  OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.            |
 |                                                                            |
 \----------------------------------------------------------------------------/

 Yosys 0.36+58 (git sha1 ea7818d31, ccache clang 14.0.0-1ubuntu1.1 -Os -flto -flto)
...
```

This seems to be due to `console.log` getting called [here](https://github.com/YoWASP/runtime-js/blob/4c7fe71d7eb4d07e3d4222995a3f16dcab486485/lib/api-base.js#L53).

I'd normally just write a patch for this but don't know what it should be, and figured I would file an issue just in case I forgot.

### PR DESCRIPTION
**Pull request by thoughtpolice**
Summary: When fetching built-in resources (e.g. techlibs) for the virtual filesystem, do it in parallel by building up an array of promises and resolving them via `Promise.all`, rather than doing so sequentially.

A nice effect of this is that it helps avoid HOL blocking when the resource might be non-local e.g. your in-browser HTTP request to a CDN or server suddenly starts having bad latency.

It also lets us get away with less logging (ref: #2), and removing these explicit `console.log` calls actually fixes an awkward case where `printLine` is set to a no-op function to keep things quiet, but these logs would still get output with no way to suppress it. (If this is ever brought back it should at least respect the `printLine` callback.)

Fixes #2.

Change-Id: Ie8085a216c22576d6956f007e2859e2381a56a12

### CODE REVIEW

**Comment by thoughtpolice** [comment]
I ran the testsuite, so I hope this is OK, but please keep my baby JavaScript skills in mind.

File: lib/api-base.js [hunk 1]
```diff
@@ -60,16 +59,21 @@ export class BaseApplication {
 
     async _fetchObject(obj, fetchFn) {
         // Mutate the object being fetched, to avoid re-fetches within the same session.
+        // Do this in parallel to avoid HOL blocking.
+        let promises = [];
```
Comment (whitequark) [inline lib/api-base.js]: The `const` is for the binding—it can still be mutated.

```suggestion
        const promises = [];
```

**Comment by whitequark** [comment]
> (If this is ever brought back it should at least respect the `printLine` callback.)

The package is primarily targeting the browser use case, where `console.log` is invisible. I agree that expanding its scope to Node/Deno is reasonable, and dropping these calls to `console.log` is also reasonable. I see no need to forward this information to `printLine`; that exists solely for the application itself, not for any debug information, since the embedder may want to interpret that info.

**Comment by whitequark** [comment]
Note that once this is merged, all packages will need to (a) have the version bumped in `package.json` and (b) be re-published, since they bundle the runtime.

**Comment by whitequark** [comment]
Thanks!

**Comment by thoughtpolice** [comment]
Thanks for the quick response! Much appreciated.
